name: Build + Publish

on: [push]
env:
  MASTER_BRANCH: UGACT-569-Migrate-To-Github-Actions
  RELEASE_BRANCH: kamils-release-branch
  DOCS_BRANCH: kamils-gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out branch ${{ github.ref }}
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use nvm version
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Build
        run: |
          yarn
          yarn run build
          yarn run docs

  publish-release:

    needs: build
    if: ${{ github.ref == 'refs/heads/$MASTER_BRANCH' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - name: Check out branch ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          path: $MASTER_BRANCH
      - name: Check out $RELEASE_BRANCH branch
        uses: actions/checkout@v2
        with:
          ref: $RELEASE_BRANCH
          path: $RELEASE_BRANCH
      - name: Read .nvmrc
        working-directory: $MASTER_BRANCH
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use nvm version
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Build
        run: |
          yarn
          yarn run build
          yarn run docs
        working-directory: $MASTER_BRANCH
      - name: Copy files to $RELEASE_BRANCH branch
        run: |
          cp -r ../$MASTER_BRANCH/dist .
          cp -r ../$MASTER_BRANCH/src .
          cp -r ../$MASTER_BRANCH/deploy .
          cp ../$MASTER_BRANCH/package.json .
          cp ../$MASTER_BRANCH/README.md .
          cp ../$MASTER_BRANCH/LICENSE.md .
          cp ../$MASTER_BRANCH/Jenkinsfile .
        working-directory: $RELEASE_BRANCH
      - name: Commit and push
        run: |
          git config user.name ${{ github.event.pusher.name }}
          git config user.email ${{ github.event.pusher.email }}
          git add . -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push
        working-directory: $RELEASE_BRANCH

  publish-docs:

    needs: build
    if: ${{ github.ref == 'refs/heads/$MASTER_BRANCH' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying branch $GITHUB_REF to $DOCS_BRANCH branch"
      - name: Check out branch ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          path: $MASTER_BRANCH
      - name: Check out $DOCS_BRANCH branch
        uses: actions/checkout@v2
        with:
          ref: $DOCS_BRANCH
          path: $DOCS_BRANCH
      - name: Read .nvmrc
        working-directory: $MASTER_BRANCH
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use nvm version
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Build
        run: |
          yarn
          yarn run build
          yarn run docs
        working-directory: $MASTER_BRANCH
      - name: Copy files to $DOCS_BRANCH branch
        run: |
          cp -r ../$MASTER_BRANCH/docs/* .
          mkdir -p docs/assets/
          mv assets/* docs/
          rmdir assets
          cp -r ../$MASTER_BRANCH/dist .
        working-directory: $DOCS_BRANCH
      - name: Commit and push
        run: |
          git config user.name ${{ github.event.pusher.name }}
          git config user.email ${{ github.event.pusher.email }}
          git add . -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push
        working-directory: $DOCS_BRANCH
