name: Build + Publish

on: [push]
env:
  MASTER_BRANCH: UGACT-569-Migrate-To-Github-Actions
  RELEASE_BRANCH: kamils-release-branch
  DOCS_BRANCH: kamils-gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out branch ${{ github.ref }}
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use nvm version
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Build
        run: |
          yarn
          yarn run build
          yarn run docs

  publish-release:

    needs: build
    if: ${{ github.ref == 'refs/heads/UGACT-569-Migrate-To-Github-Actions' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying ${{ github.ref }} to ${{env.RELEASE_BRANCH}} branch"
      - name: Check out branch ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          path: ${{env.MASTER_BRANCH}}
      - name: Check out ${{env.RELEASE_BRANCH}} branch
        uses: actions/checkout@v2
        with:
          ref: ${{env.RELEASE_BRANCH}}
          path: ${{env.RELEASE_BRANCH}}
      - name: Read .nvmrc
        working-directory: ${{env.MASTER_BRANCH}}
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use nvm version
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Build
        run: |
          yarn
          yarn run build
          yarn run docs
        working-directory: ${{env.MASTER_BRANCH}}
      - name: Copy files to ${{env.RELEASE_BRANCH}} branch
        run: |
          cp -r ../${{env.MASTER_BRANCH}}/dist .
          cp -r ../${{env.MASTER_BRANCH}}/src .
          cp -r ../${{env.MASTER_BRANCH}}/deploy .
          cp ../${{env.MASTER_BRANCH}}/package.json .
          cp ../${{env.MASTER_BRANCH}}/README.md .
          cp ../${{env.MASTER_BRANCH}}/LICENSE.md .
          cp ../${{env.MASTER_BRANCH}}/Jenkinsfile .
        working-directory: ${{env.RELEASE_BRANCH}}
      - name: Commit and push
        run: |
          git config user.name ${{ github.event.pusher.name }}
          git config user.email ${{ github.event.pusher.email }}
          git add . -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push
        working-directory: ${{env.RELEASE_BRANCH}}

  publish-docs:

    needs: build
    if: ${{ github.ref == 'refs/heads/UGACT-569-Migrate-To-Github-Actions' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying ${{ github.ref }} to ${{env.DOCS_BRANCH}} branch"
      - name: Check out branch ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          path: ${{env.MASTER_BRANCH}}
      - name: Check out ${{env.DOCS_BRANCH}} branch
        uses: actions/checkout@v2
        with:
          ref: ${{env.DOCS_BRANCH}}
          path: ${{env.DOCS_BRANCH}}
      - name: Read .nvmrc
        working-directory: ${{env.MASTER_BRANCH}}
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use nvm version
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Build
        run: |
          yarn
          yarn run build
          yarn run docs
        working-directory: ${{env.MASTER_BRANCH}}
      - name: Copy files to ${{env.DOCS_BRANCH}} branch
        run: |
          cp -r ../${{env.MASTER_BRANCH}}/docs/* .
          mkdir -p docs/assets/
          mv assets/* docs/
          rmdir assets
          cp -r ../${{env.MASTER_BRANCH}}/dist .
        working-directory: ${{env.DOCS_BRANCH}}
      - name: Commit and push
        run: |
          git config user.name ${{ github.event.pusher.name }}
          git config user.email ${{ github.event.pusher.email }}
          git add . -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push
        working-directory: ${{env.DOCS_BRANCH}}
