name: Build + Publish

on: [push]
env:
  MASTER_BRANCH: UGACT-569-Migrate-To-Github-Actions
  RELEASE_BRANCH: kamils-release-branch
  DOCS_BRANCH: kamils-gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out branch ${{ github.ref }}
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use nvm version
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Build
        run: |
          yarn
          yarn run build
          yarn run docs
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            dist
            src
            deploy
            docs
            package.json
            README.md
            LICENSE.md
            Jenkinsfile
          retention-days: 1

  publish-release:

    needs: build
    if: ${{ github.ref == 'refs/heads/UGACT-569-Migrate-To-Github-Actions' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying ${{ github.ref }} to ${{env.RELEASE_BRANCH}} branch"
      - name: Check out ${{env.RELEASE_BRANCH}} branch
        uses: actions/checkout@v2
        with:
          ref: ${{env.RELEASE_BRANCH}}
          path: ${{env.RELEASE_BRANCH}}
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: artifacts
      - name: Copy files to ${{env.RELEASE_BRANCH}} branch
        run: |
          cp -r ../artifacts/dist .
          cp -r ../artifacts/src .
          cp -r ../artifacts/deploy .
          cp ../artifacts/package.json .
          cp ../artifacts/README.md .
          cp ../artifacts/LICENSE.md .
          cp ../artifacts/Jenkinsfile .
        working-directory: ${{env.RELEASE_BRANCH}}
      - name: Commit and push
        run: |
          git config user.name ${{ github.event.pusher.name }}
          git config user.email ${{ github.event.pusher.email }}
          git add . -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push
        working-directory: ${{env.RELEASE_BRANCH}}

  publish-docs:

    needs: build
    if: ${{ github.ref == 'refs/heads/UGACT-569-Migrate-To-Github-Actions' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying ${{ github.ref }} to ${{env.DOCS_BRANCH}} branch"
      - name: Check out ${{env.DOCS_BRANCH}} branch
        uses: actions/checkout@v2
        with:
          ref: ${{env.DOCS_BRANCH}}
          path: ${{env.DOCS_BRANCH}}
      - name: download dist artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: artifacts/dist
      - name: download docs artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: artifacts/dist
      - name: Copy files to ${{env.DOCS_BRANCH}} branch
        run: |
          cp -r ../docs/* .
          mkdir -p docs/assets/
          mv assets/* docs/
          rmdir assets
          cp -r ../dist .
        working-directory: ${{env.DOCS_BRANCH}}
      - name: Commit and push
        run: |
          git config user.name ${{ github.event.pusher.name }}
          git config user.email ${{ github.event.pusher.email }}
          git add . -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push
        working-directory: ${{env.DOCS_BRANCH}}
